allowed-duplicate-crates = [
    "axum",
    "axum-core",
    "base64",
    "getrandom",
    "hashbrown",
    "indexmap",
    "matchit",
    "regex-automata",
    "regex-syntax",
    "rand",
    "rand_chacha",
    "rand_core",
    "sync_wrapper",
    "tower",
    "wasi",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "zerocopy",
    "zerocopy-derive",
]
